export const digitalProductPlanOrder = {
  basic: 1,
  personal: 2,
  private_business: 3,
};

export const digitalProductPlanLabels = {
  basic: "Bazinis",
  personal: "Asmeninis",
  private_business: "Privatus verslas",
};

export const digitalProducts = [
  {
    id: "finance-clarity-starter-kit",
    title: "Mėnesio finansų aiškumo starter kit",
    description:
      "Premium PDF rinkinys mėnesio finansų apžvalgai, pajamų ir išlaidų lentelei, taupymo blokui ir savaitės veiksmų planui.",
    type: "Premium PDF starter kit",
    planLevel: "basic",
    planLabel: "Visiems nariams",
    valueSummary: "Padeda mėnesį pradėti su aiškiais skaičiais, taupymo kryptimi ir konkrečiais savaitės veiksmais.",
    fileUrl: "/resources/digital-products/bazinis/stilloak-finansu-aiskumo-starter-kit.pdf",
    fileName: "stilloak-finansu-aiskumo-starter-kit.pdf",
    badge: "PDF starter kit",
    isPremium: true,
    isActive: true,
  },
  {
    id: "personal-spending-audit-checklist",
    title: "Asmeninių išlaidų audito checklist",
    description:
      "Premium PDF checklist prenumeratų, kasdienių išlaidų, impulsyvių pirkinių ir nereikalingų mokėjimų auditui.",
    type: "Premium PDF checklist",
    planLevel: "basic",
    planLabel: "Visiems nariams",
    valueSummary: "Suteikia aiškią eigą, ką peržiūrėti, ką sumažinti ir kokį sprendimą priimti šį mėnesį.",
    fileUrl: "/resources/digital-products/bazinis/stilloak-islaidu-audito-checklist.pdf",
    fileName: "stilloak-islaidu-audito-checklist.pdf",
    badge: "PDF checklist",
    isPremium: true,
    isActive: true,
  },
  {
    id: "savings-goal-planning-template",
    title: "Taupymo tikslų planavimo šablonas",
    description:
      "Premium PDF šablonas taupymo tikslui, reikalingai sumai, terminui, mėnesiniam įnašui ir progresui sekti.",
    type: "Premium PDF worksheet",
    planLevel: "basic",
    planLabel: "Visiems nariams",
    valueSummary: "Padeda tikslą paversti aiškia suma, terminu, mėnesio įnašu ir matomu progresu.",
    fileUrl: "/resources/digital-products/bazinis/stilloak-taupymo-tikslu-planavimo-sablonas.pdf",
    fileName: "stilloak-taupymo-tikslu-planavimo-sablonas.pdf",
    badge: "PDF worksheet",
    isPremium: true,
    isActive: true,
  },
  {
    id: "premium-financial-goals-system",
    title: "Premium finansinių tikslų sistema",
    description:
      "Premium PDF sistema 90 dienų tikslams, finansiniams įpročiams, mėnesio sprendimams, progresui ir analizei.",
    type: "Premium PDF system",
    planLevel: "personal",
    planLabel: "Asmeninis+",
    valueSummary: "Sujungia tikslus, pinigų įpročius, sprendimų filtrą ir progreso sekimą į vieną aiškią sistemą.",
    fileUrl: "/resources/digital-products/asmeninis/stilloak-premium-finansiniu-tikslu-sistema.pdf",
    fileName: "stilloak-premium-finansiniu-tikslu-sistema.pdf",
    badge: "PDF sistema",
    isPremium: true,
    isActive: true,
  },
  {
    id: "digital-product-idea-framework",
    title: "Skaitmeninių produktų idėjų vertinimo framework",
    description:
      "Premium PDF worksheet idėjai įvertinti pagal auditoriją, problemą, vertės pažadą, skirtumą, MVP paprastumą ir kainodarą.",
    type: "Premium PDF framework",
    planLevel: "personal",
    planLabel: "Asmeninis+",
    valueSummary: "Leidžia greitai pamatyti, ar produkto idėja turi aiškų pirkimo motyvą ir realų paleidimo potencialą.",
    fileUrl: "/resources/digital-products/asmeninis/stilloak-skaitmeniniu-produktu-ideju-framework.pdf",
    fileName: "stilloak-skaitmeniniu-produktu-ideju-framework.pdf",
    badge: "PDF framework",
    isPremium: true,
    isActive: true,
  },
  {
    id: "income-expense-optimization-plan",
    title: "Pajamų ir išlaidų optimizavimo planas",
    description:
      "Premium PDF planas pajamų šaltinių apžvalgai, išlaidų kategorijų analizei, prioritetams ir 30 dienų veiksmams.",
    type: "Premium PDF plan",
    planLevel: "personal",
    planLabel: "Asmeninis+",
    valueSummary: "Padeda pasirinkti, ką mažinti, ką stiprinti ir kokį optimizavimo veiksmą atlikti per artimiausias 30 dienų.",
    fileUrl: "/resources/digital-products/asmeninis/stilloak-pajamu-ir-islaidu-optimizavimo-planas.pdf",
    fileName: "stilloak-pajamu-ir-islaidu-optimizavimo-planas.pdf",
    badge: "PDF planas",
    isPremium: true,
    isActive: true,
  },
  {
    id: "mini-business-launch-blueprint",
    title: "Mini verslo paleidimo blueprint",
    description:
      "Premium PDF blueprint idėjai, auditorijai, problemai, sprendimui, pasiūlymui, pirmam produktui ir 14 dienų planui.",
    type: "Premium PDF blueprint",
    planLevel: "private_business",
    planLabel: "Privatus verslas",
    valueSummary: "Padeda išskaidyti verslo idėją į aiškų pirmą pasiūlymą ir paleidimo veiksmų seką.",
    fileUrl: "/resources/digital-products/privatus-verslas/stilloak-mini-verslo-paleidimo-blueprint.pdf",
    fileName: "stilloak-mini-verslo-paleidimo-blueprint.pdf",
    badge: "PDF blueprint",
    isPremium: true,
    isActive: true,
  },
  {
    id: "digital-product-launch-kit",
    title: "Digital Product Launch Kit",
    description:
      "Premium PDF launch kit produkto struktūrai, paleidimo checklistui, timeline, puslapio tekstams ir CTA pavyzdžiams.",
    type: "Premium PDF launch kit",
    planLevel: "private_business",
    planLabel: "Privatus verslas",
    valueSummary: "Sutrumpina kelią nuo produkto idėjos iki aiškaus pristatymo, paleidimo plano ir final kontrolės.",
    fileUrl: "/resources/digital-products/privatus-verslas/stilloak-digital-product-launch-kit.pdf",
    fileName: "stilloak-digital-product-launch-kit.pdf",
    badge: "PDF launch kit",
    isPremium: true,
    isActive: true,
  },
  {
    id: "premium-offer-framework",
    title: "Premium produkto pasiūlymo framework",
    description:
      "Premium PDF framework produkto pavadinimui, auditorijai, problemai, pagrindinei naudai, kainodarai ir CTA tekstams.",
    type: "Premium PDF offer framework",
    planLevel: "private_business",
    planLabel: "Privatus verslas",
    valueSummary: "Padeda produktą paversti aiškiu, stipriu ir premium jausmą turinčiu pasiūlymu.",
    fileUrl: "/resources/digital-products/privatus-verslas/stilloak-premium-produkto-pasiulymo-framework.pdf",
    fileName: "stilloak-premium-produkto-pasiulymo-framework.pdf",
    badge: "PDF offer framework",
    isPremium: true,
    isActive: true,
  },
  {
    id: "store-page-copy-kit",
    title: "Store Page Copy Kit",
    description:
      "Premium PDF copy kit hero tekstams, produkto aprašymui, naudų blokams, FAQ, pirkimo CTA ir pasitikėjimo tekstams.",
    type: "Premium PDF copy kit",
    planLevel: "private_business",
    planLabel: "Privatus verslas",
    valueSummary: "Suteikia aiškią puslapio tekstų struktūrą, kad produktas būtų lengviau suprantamas ir perkamas.",
    fileUrl: "/resources/digital-products/privatus-verslas/stilloak-store-page-copy-kit.pdf",
    fileName: "stilloak-store-page-copy-kit.pdf",
    badge: "PDF copy kit",
    isPremium: true,
    isActive: true,
  },
];
