const buildDownloadUrl = (folder, id, extension) => `/digital-products/${folder}/${id}.${extension}`;

export const digitalProducts = [
  {
    id: "personal-budget-system",
    title: "Personal Budget System",
    subtitle: "Mėnesio biudžeto sistema pajamoms, išlaidoms, tikslams ir balansui.",
    description:
      "Praktinis PDF gidas paaiškina, kaip naudoti Excel modelį su formulėmis pajamoms, išlaidoms, taupymo tikslams ir mėnesio likučiui sekti.",
    category: "Finansai",
    formats: ["PDF", "XLSX"],
    includedItems: [
      "PDF gidas su aiškia mėnesio biudžeto naudojimo eiga",
      "Excel modelis su formulėmis pajamoms, išlaidoms ir balansui skaičiuoti",
      "Taupymo tikslų ir mėnesio progreso sekimo lapai",
      "Peržiūros klausimai geresniems mėnesio pabaigos sprendimams",
    ],
    pdfDownloadUrl: buildDownloadUrl("pdf", "personal-budget-system", "pdf"),
    excelDownloadUrl: buildDownloadUrl("excel", "personal-budget-system", "xlsx"),
    requiredPlan: "basic",
    isPublic: true,
    premiumCtaText: "Pradėkite nuo Demo versijos, o Asmeninis planas atrakins gilesnius finansų įrankius.",
  },
  {
    id: "12-month-savings-tracker",
    title: "12-Month Savings Tracker",
    subtitle: "Metinis trackeris planuojamoms įmokoms, progresui ir taupymo įpročiams.",
    description:
      "PDF gidas parodo, kaip suplanuoti taupymo ritmą, o Excel modelis su formulėmis seka tikslą, įmokas, skirtumą ir bendrą progresą.",
    category: "Finansai",
    formats: ["PDF", "XLSX"],
    includedItems: [
      "PDF gidas taupymo tikslui, mėnesio ritmui ir peržiūrai nusistatyti",
      "Excel modelis su formulėmis planuotoms ir realioms įmokoms palyginti",
      "12 mėnesių progreso vaizdas ir bendro balanso sekimas",
      "Įpročių klausimai, kad taupymą būtų lengviau kartoti",
    ],
    pdfDownloadUrl: buildDownloadUrl("pdf", "12-month-savings-tracker", "pdf"),
    excelDownloadUrl: buildDownloadUrl("excel", "12-month-savings-tracker", "xlsx"),
    requiredPlan: "basic",
    isPublic: true,
    premiumCtaText: "Naudokite trackerį Demo versijoje, o narystėje atrakinkite išsamesnį taupymo planavimą.",
  },
  {
    id: "weekly-planning-system",
    title: "Weekly Planning System",
    subtitle: "Savaitės sistema tikslams, prioritetams, užduotims ir progresui.",
    description:
      "Praktinis PDF gidas padeda susidėlioti savaitės ritmą, o Excel modelis su formulėmis seka užduotis, prioritetus ir užbaigimo progresą.",
    category: "Planavimas",
    formats: ["PDF", "XLSX"],
    includedItems: [
      "PDF gidas savaitės tikslams, prioritetams ir refleksijai",
      "Excel modelis su formulėmis užduočių progresui ir užbaigimui sekti",
      "Prioritetų, terminų, būsenų ir peržiūros pastabų struktūra",
      "Savaitės pabaigos klausimai fokusui ir kitam žingsniui išsigryninti",
    ],
    pdfDownloadUrl: buildDownloadUrl("pdf", "weekly-planning-system", "pdf"),
    excelDownloadUrl: buildDownloadUrl("excel", "weekly-planning-system", "xlsx"),
    requiredPlan: "basic",
    isPublic: true,
    premiumCtaText: "Pradėkite nuo savaitės planavimo, o narystėje atrakinkite gilesnę asmeninę sistemą.",
  },
  {
    id: "business-idea-validation-kit",
    title: "Business Idea Validation Kit",
    subtitle: "Verslo idėjos patikra paklausai, kainai, auditorijai ir kitam žingsniui.",
    description:
      "PDF gidas paaiškina, kaip vertinti idėją, o Excel modelis su formulėmis padeda balais įsivertinti paklausą, kainodarą ir paleidimo aiškumą.",
    category: "Verslas",
    formats: ["PDF", "XLSX"],
    includedItems: [
      "PDF validavimo gidas paklausai, auditorijai, pasiūlymui ir kainai",
      "Excel modelis su formulėmis idėjos stiprumui ir rizikai įvertinti",
      "Klausimų rinkinys pirkimo motyvui ir testavimo krypčiai patikrinti",
      "Sprendimo lentelė, ką verta testuoti pirmiausia",
    ],
    pdfDownloadUrl: buildDownloadUrl("pdf", "business-idea-validation-kit", "pdf"),
    excelDownloadUrl: buildDownloadUrl("excel", "business-idea-validation-kit", "xlsx"),
    requiredPlan: "private_business",
    isPublic: true,
    premiumCtaText: "Patikrinkite idėją Verslas plane ir atrakinkite daugiau paleidimo resursų.",
  },
  {
    id: "social-media-content-calendar",
    title: "Social Media Content Calendar",
    subtitle: "Turinio kalendorius Instagram, TikTok, YouTube Shorts ir savaitės planui.",
    description:
      "PDF gidas paaiškina turinio planavimo ritmą, o Excel modelis su formulėmis padeda sekti temas, kanalus, būsenas ir savaitės rezultatą.",
    category: "Marketingas",
    formats: ["PDF", "XLSX"],
    includedItems: [
      "PDF gidas turinio temoms, savaitės ritmui ir peržiūrai",
      "Excel modelis su formulėmis įrašų būsenai ir savaitės progresui sekti",
      "Instagram, TikTok ir YouTube Shorts planavimo laukai",
      "Savaitiniai klausimai turiniui išlaikyti kryptingam ir naudingam",
    ],
    pdfDownloadUrl: buildDownloadUrl("pdf", "social-media-content-calendar", "pdf"),
    excelDownloadUrl: buildDownloadUrl("excel", "social-media-content-calendar", "xlsx"),
    requiredPlan: "personal",
    isPublic: true,
    premiumCtaText: "Planuokite turinį Asmeniniame plane, o Verslas atrakina papildomus verslo įrankius.",
  },
];
