const sharedProductMeta = {
  formats: ["XLSX"],
  lastUpdated: "2026",
  isPublic: true,
  isPaid: true,
  productType: "digital_download",
  stripePriceEnvKey: null,
  stripePriceIdReference: "dynamic_one_time_checkout",
  ctaLabels: {
    guest: "Prisiregistruoti ir įsigyti",
    purchase: "Pirkti dabar",
    download: "Atsisiųsti Excel",
  },
};

export const digitalProducts = [
  {
    ...sharedProductMeta,
    id: "personal-budget-system",
    slug: "stilloak-personal-budget-system",
    title: "StillOak Personal Budget System",
    subtitle: "Premium asmeninio biudžeto Excel sistema aiškesniam pinigų valdymui.",
    description:
      "Profesionalus Excel modelis pajamoms, išlaidoms, kategorijoms, taupymo tikslams ir mėnesio balansui valdyti vienoje aiškioje sistemoje.",
    salesDescription:
      "Sukurtas žmonėms, kurie nori matyti realų finansų vaizdą be chaoso. Įveskite planą, faktinius skaičius ir taupymo tikslus, o dashboard padės greitai suprasti, kur pinigai juda gerai ir kur verta koreguoti įpročius.",
    category: "Finansai",
    priceLabel: "€19",
    priceCents: 1900,
    version: "V10",
    imageUrl: "/digital-products/previews/personal-budget-system-preview.png",
    pdfFileName: null,
    excelFileName: "StillOak_Personal_Budget_System.xlsx",
    highlightBadge: "Geriausia pradžiai",
    badges: ["Excel", "Su formulėmis", "Automatinis dashboard", "Finansai"],
    trustBadges: ["Saugus pirkimas", "Skaitmeninis atsisiuntimas", "Prieiga po apmokėjimo", "Paruošta naudoti"],
    benefits: [
      "Aiškiai parodo mėnesio pajamas, išlaidas ir balansą.",
      "Padeda pastebėti, kurios kategorijos viršija planą.",
      "Sujungia taupymo tikslus ir progresą vienoje vietoje.",
      "Suteikia paruoštą dashboard be papildomo kūrimo darbo.",
      "Tinka asmeniniam arba namų ūkio biudžetui.",
    ],
    includedItems: [
      "Excel biudžeto modelis su formulėmis",
      "Pajamų ir išlaidų sekimo lentelės",
      "Kategorijų analizė",
      "Taupymo tikslų sistema",
      "Automatinis mėnesio dashboard",
      "Monthly Review darbo lapas",
    ],
    whatsIncluded: [
      "Dashboard su pagrindiniais biudžeto rodikliais",
      "Income, Expenses ir Savings Goals lapai",
      "Category Summary analizė",
      "Start Here naudojimosi instrukcija",
      "Settings lapas kategorijoms ir statusams",
    ],
    targetAudience: [
      "Žmonėms, kurie nori tvarkingai valdyti asmeninį biudžetą.",
      "Poroms ar namų ūkiams, norintiems matyti bendrą finansų vaizdą.",
      "Pradedantiesiems, kuriems reikia aiškios struktūros be sudėtingo pasiruošimo.",
      "Visiems, kurie nori kas mėnesį priimti ramesnius finansinius sprendimus.",
    ],
    howToUseSteps: [
      "Atsidarykite Start Here lapą ir peržiūrėkite naudojimosi eigą.",
      "Įveskite mėnesio pajamas, išlaidas ir taupymo tikslus.",
      "Dashboard lape stebėkite balansą, kategorijas ir progresą.",
    ],
    excelFeatures: [
      "Automatiniai pajamų ir išlaidų skaičiavimai",
      "Kategorijų analizė",
      "Taupymo tikslų progreso formulės",
      "Biudžeto dashboard",
      "Mėnesio peržiūros struktūra",
    ],
    dashboardMetrics: [
      "Total Income",
      "Total Expenses",
      "Monthly Balance",
      "Savings Rate",
      "Category Analysis",
      "Savings Goals",
    ],
    estimatedUseTime: "30-45 min.",
    difficultyLevel: "Lengvas",
    fileNotes: "Mokamas Excel modelis. Atsisiuntimas pasiekiamas tik po sėkmingo pirkimo.",
  },
  {
    ...sharedProductMeta,
    id: "12-month-savings-tracker",
    slug: "stilloak-savings-tracker",
    title: "StillOak Savings Tracker",
    subtitle: "Premium taupymo trackeris tikslams, įmokoms ir progresui sekti.",
    description:
      "Švari taupymo sistema, padedanti nusistatyti tikslą, sekti įmokas, išlaikyti discipliną ir matyti, kiek liko iki rezultato.",
    salesDescription:
      "Modelis padeda taupyti ne iš nuojautos, o pagal aiškų ritmą. Susidėkite tikslą, stebėkite planuotas ir realias įmokas, matykite progresą ir laiku koreguokite tempą, kai mėnuo nukrypsta nuo plano.",
    category: "Finansai",
    priceLabel: "€15",
    priceCents: 1500,
    version: "V15",
    imageUrl: "/digital-products/previews/savings-tracker-preview.png",
    pdfFileName: null,
    excelFileName: "StillOak_Savings_Tracker.xlsx",
    highlightBadge: "Populiaru",
    badges: ["Excel", "Su formulėmis", "Automatinis dashboard", "Finansai"],
    trustBadges: ["Saugus pirkimas", "Skaitmeninis atsisiuntimas", "Prieiga po apmokėjimo", "Paruošta naudoti"],
    benefits: [
      "Suskaido didesnį tikslą į aiškius mėnesio veiksmus.",
      "Parodo planuotų ir realių įmokų skirtumus.",
      "Automatiškai skaičiuoja progresą ir likusią sumą.",
      "Padeda išlaikyti taupymo ritmą visus metus.",
      "Tinka emergency fund, kelionei, pirkiniui ar kitam tikslui.",
    ],
    includedItems: [
      "12 mėnesių taupymo trackeris",
      "Goal Setup lapas",
      "Monthly Tracker su formulėmis",
      "Milestones ir Scenario Planner lapai",
      "Review & Notes struktūra",
      "Automatinis dashboard",
    ],
    whatsIncluded: [
      "Metinio taupymo tikslo planavimas",
      "Mėnesio įmokų sekimas",
      "Progreso ir likučio skaičiavimai",
      "Scenarijų planavimo lapas",
      "Review & Notes lapas sprendimams fiksuoti",
    ],
    targetAudience: [
      "Žmonėms, kurie taupo konkrečiam tikslui.",
      "Pradedantiesiems, norintiems paprastos metinės struktūros.",
      "Tiems, kurie nori matyti ne tik sumą, bet ir taupymo tempą.",
      "Vartotojams, kuriems svarbus aiškus progreso dashboard.",
    ],
    howToUseSteps: [
      "Įveskite tikslinę sumą ir norimą taupymo laikotarpį.",
      "Kas mėnesį pildykite planuotą ir realią įmoką.",
      "Dashboard lape stebėkite progresą ir koreguokite kitą mėnesį.",
    ],
    excelFeatures: [
      "Metinio tikslo formulės",
      "Planuotų ir realių įmokų palyginimas",
      "Progreso procentas",
      "Scenarijų planavimas",
      "Automatinė apžvalga",
    ],
    dashboardMetrics: [
      "Target Amount",
      "Saved Amount",
      "Remaining Amount",
      "Monthly Progress",
      "Milestones",
      "Scenario View",
    ],
    estimatedUseTime: "20-30 min.",
    difficultyLevel: "Lengvas",
    fileNotes: "Mokamas Excel modelis. Atsisiuntimas pasiekiamas tik po sėkmingo pirkimo.",
  },
  {
    ...sharedProductMeta,
    id: "weekly-planning-system",
    slug: "stilloak-weekly-planning-system",
    title: "StillOak Weekly Planning System",
    subtitle: "Premium savaitės planavimo sistema prioritetams, užduotims ir fokusui valdyti.",
    description:
      "Profesionalus savaitės planavimo Excel modelis, padedantis susidėlioti prioritetus, valdyti užduotis ir aiškiai matyti savaitės progresą.",
    salesDescription:
      "Sukurtas žmonėms, kurie nori mažiau chaoso ir daugiau krypties. Modelis sujungia savaitės tikslus, prioritetus, užduočių eigą ir refleksiją į vieną aiškų planavimo ritmą.",
    category: "Planavimas",
    priceLabel: "€12",
    priceCents: 1200,
    version: "V15",
    imageUrl: "/digital-products/previews/weekly-planning-system-preview.png",
    pdfFileName: null,
    excelFileName: "StillOak_Weekly_Planning_System.xlsx",
    highlightBadge: "Planavimui",
    badges: ["Excel", "Su formulėmis", "Automatinis dashboard", "Planavimas"],
    trustBadges: ["Saugus pirkimas", "Skaitmeninis atsisiuntimas", "Prieiga po apmokėjimo", "Paruošta naudoti"],
    benefits: [
      "Padeda susidėlioti savaitės prioritetus prieš prasidedant darbams.",
      "Suteikia aiškų užduočių, terminų ir statusų vaizdą.",
      "Parodo savaitės progresą ir fokuso kokybę.",
      "Padeda užbaigti savaitę su refleksija ir kitu veiksmu.",
      "Tinka darbui, mokslams, projektams ar asmeniniams tikslams.",
    ],
    includedItems: [
      "Weekly Plan lapas",
      "Task Tracker su formulėmis",
      "Priority Matrix",
      "Weekly Review lapas",
      "Settings struktūra",
      "Automatinis dashboard",
    ],
    whatsIncluded: [
      "Savaitės tikslų ir prioritetų planavimas",
      "Užduočių sekimas pagal statusą ir prioritetą",
      "Prioritetų matrica",
      "Savaitės peržiūros klausimai",
      "Dashboard su progreso rodikliais",
    ],
    targetAudience: [
      "Žmonėms, kurie nori planuoti savaitę aiškiau ir ramiau.",
      "Freelanceriams, kūrėjams ir specialistams su daug skirtingų užduočių.",
      "Tiems, kurie nori matyti progresą, o ne tik užduočių sąrašą.",
      "Vartotojams, kuriems reikia paprastos, bet profesionalios planavimo sistemos.",
    ],
    howToUseSteps: [
      "Pradėkite nuo Weekly Plan ir pasirinkite pagrindinius savaitės prioritetus.",
      "Task Tracker lape pildykite užduotis, statusus ir terminus.",
      "Savaitės pabaigoje užpildykite Weekly Review ir suplanuokite kitą žingsnį.",
    ],
    excelFeatures: [
      "Užduočių progreso formulės",
      "Prioritetų ir statusų struktūra",
      "Dashboard su savaitės rodikliais",
      "Weekly Review darbo eiga",
      "Planavimo lapai be makrokomandų",
    ],
    dashboardMetrics: [
      "Weekly Focus",
      "Task Progress",
      "Priority Mix",
      "Completion Rate",
      "Review Notes",
      "Next Actions",
    ],
    estimatedUseTime: "15-25 min.",
    difficultyLevel: "Lengvas",
    fileNotes: "Mokamas Excel modelis. Atsisiuntimas pasiekiamas tik po sėkmingo pirkimo.",
  },
];
