export const productivityResources = [
  {
    id: "productivity-starter-kit",
    title: "Produktyvumo Starter Kit",
    type: "PDF workbook + CSV template",
    description: "Pilnas pradžios rinkinys dienos, savaitės, tikslų ir įpročių planavimui.",
    valueSummary: "Padeda greitai susidėti aiškų planavimo ritmą: nuo dienos fokuso iki 30 dienų veiksmų plano.",
    badge: "Nemokama",
    includes: [
      "Dienos planavimo puslapis",
      "Savaitės planavimo sistema",
      "Prioritetų matrica",
      "30 dienų veiksmų planas",
      "Refleksijos klausimai",
      "CSV trackeris progresui sekti",
    ],
    files: [
      {
        label: "PDF workbook",
        format: "PDF",
        fileUrl: "/resources/productivity/stilloak-productivity-starter-kit.pdf",
        fileName: "stilloak-productivity-starter-kit.pdf",
      },
      {
        label: "CSV trackeris",
        format: "CSV / Excel",
        fileUrl: "/resources/productivity/stilloak-productivity-starter-kit.csv",
        fileName: "stilloak-productivity-starter-kit.csv",
      },
    ],
    isActive: true,
  },
  {
    id: "thirty-day-productivity-planner",
    title: "30 dienų produktyvumo planuoklis",
    type: "PDF planner",
    description: "30 dienų struktūra užduotims, prioritetams, įpročiams ir savaitės peržiūrai.",
    valueSummary: "Padeda matyti ne tik darbų sąrašą, bet ir dienos fokusą, produktyvumo balą bei kitą savaitės veiksmą.",
    badge: "Nemokama",
    includes: [
      "Kasdieniai prioritetai",
      "Dienos fokusas",
      "Savaitės refleksija",
      "Produktyvumo balas",
      "Veiksmo planas kitai savaitei",
    ],
    files: [
      {
        label: "PDF planner",
        format: "PDF",
        fileUrl: "/resources/productivity/stilloak-30-day-productivity-planner.pdf",
        fileName: "stilloak-30-day-productivity-planner.pdf",
      },
    ],
    isActive: true,
  },
  {
    id: "weekly-planner-pro",
    title: "Weekly Planner Pro",
    type: "PDF + CSV",
    description: "Savaitės planavimo šablonas darbams, mokslams, projektams ir asmeniniams tikslams.",
    valueSummary: "Sujungia savaitės tikslus, pagrindinius prioritetus, terminus ir rezultatų peržiūrą į vieną aiškų ritmą.",
    badge: "Nemokama",
    includes: [
      "Savaitės tikslai",
      "Pagrindiniai prioritetai",
      "Užduočių lentelė",
      "Terminų blokas",
      "Savaitės rezultatų peržiūra",
    ],
    files: [
      {
        label: "PDF planuoklis",
        format: "PDF",
        fileUrl: "/resources/productivity/stilloak-weekly-planner-pro.pdf",
        fileName: "stilloak-weekly-planner-pro.pdf",
      },
      {
        label: "CSV šablonas",
        format: "CSV / Excel",
        fileUrl: "/resources/productivity/stilloak-weekly-planner-pro.csv",
        fileName: "stilloak-weekly-planner-pro.csv",
      },
    ],
    isActive: true,
  },
  {
    id: "habit-tracker",
    title: "Habit Tracker",
    type: "PDF + CSV",
    description: "Įpročių sekimo sistema, skirta stebėti progresą ir išlaikyti ritmą.",
    valueSummary: "Padeda vienoje vietoje matyti įpročio dažnumą, 30 dienų progresą, procentą ir refleksijos klausimus.",
    badge: "Nemokama",
    includes: [
      "Įpročio pavadinimas",
      "Dažnumas",
      "30 dienų sekimas",
      "Progreso procentas",
      "Refleksijos klausimai",
    ],
    files: [
      {
        label: "PDF trackeris",
        format: "PDF",
        fileUrl: "/resources/productivity/stilloak-habit-tracker.pdf",
        fileName: "stilloak-habit-tracker.pdf",
      },
      {
        label: "CSV trackeris",
        format: "CSV / Excel",
        fileUrl: "/resources/productivity/stilloak-habit-tracker.csv",
        fileName: "stilloak-habit-tracker.csv",
      },
    ],
    isActive: true,
  },
  {
    id: "time-blocking-template",
    title: "Time Blocking Template",
    type: "CSV / Excel-compatible template",
    description: "Laiko blokavimo šablonas dienai susidėlioti pagal darbo, poilsio, mokymosi ir asmeninius blokus.",
    valueSummary: "Padeda dieną suplanuoti valandų blokais, priskirti prioritetą, energijos lygį ir dienos santrauką.",
    badge: "Nemokama",
    includes: [
      "Valandų blokai",
      "Užduotys",
      "Prioritetas",
      "Energijos lygis",
      "Atlikta / neatlikta statusas",
      "Dienos santrauka",
    ],
    files: [
      {
        label: "CSV šablonas",
        format: "CSV / Excel",
        fileUrl: "/resources/productivity/stilloak-time-blocking-template.csv",
        fileName: "stilloak-time-blocking-template.csv",
      },
    ],
    isActive: true,
  },
];
