export const subscriptionPlans = [
  {
    id: "basic",
    name: "Bazinis",
    price: 5.99,
    intervalLabel: "/mėn.",
    description: "Paprasta pradžia mėnesio planui ir baziniams resursams.",
    provider: "stripe",
    badge: "Pradžia",
    features: [
      "Mėnesio fokusas",
      "Mini biudžeto peržiūra",
      "Baziniai resursai",
      "Stilloak Start Kit",
      "Šios savaitės veiksmas",
    ],
  },
  {
    id: "personal",
    name: "Asmeninis",
    price: 15.99,
    intervalLabel: "/mėn.",
    description: "Pilna nario erdvė su suvestinėmis, tikslais ir premium resursais.",
    provider: "stripe",
    badge: "Populiariausias",
    features: [
      "Pilna nario zona",
      "Mėnesio suvestinės",
      "Tikslų progreso kortelės",
      "Nario naujienos",
      "Stilloak Growth Kit",
      "Premium resursai",
    ],
  },
  {
    id: "private_business",
    name: "Privatus verslas",
    price: 44.99,
    intervalLabel: "/mėn.",
    description: "Strateginė verslo erdvė pasiūlymui, auditui ir augimo planui.",
    provider: "stripe",
    badge: "Aukščiausias lygis",
    features: [
      "Strategijos lenta",
      "Pasiūlymo aiškumas",
      "Svetainės auditas",
      "30 dienų augimo planas",
      "Stilloak Business Kit",
      "Strategijos santrauka",
    ],
  },
];
