export const subscriptionPlans = [
  {
    id: "free",
    name: "Guest",
    price: 0,
    intervalLabel: "/ always",
    description: "Trumpa įžanga į Stilloak pasaulį prieš pasirenkant pilną narystę.",
    provider: "internal",
    badge: "Entry",
    features: ["Private account", "Launch previews", "Secure checkout history"],
  },
  {
    id: "circle",
    name: "Circle",
    price: 10,
    intervalLabel: "/ month",
    description: "Pagrindinė narystė pilnai Stilloak patirčiai: aiškesniems mėnesiams, tikslams ir privačiam archyvui.",
    provider: "stripe",
    badge: "Most loved",
    features: [
      "Full Stilloak dashboard",
      "Budgets, goals, and recurring spend",
      "CSV import and monthly overview",
      "Weekly and monthly summaries",
      "Members-only Journal",
      "Priority account care",
    ],
  },
  {
    id: "private",
    name: "Private",
    price: 20,
    intervalLabel: "/ month",
    description: "Aukštesnis narystės lygis tiems, kurie nori daugiau priežiūros, ramybės ir prioriteto.",
    provider: "stripe",
    badge: "Signature",
    features: [
      "Everything in Circle",
      "Priority member care",
      "Private-tier billing support",
      "Members-only Journal",
      "Early access when releases open",
      "Best for deeper ongoing use",
    ],
  },
];
