export const subscriptionPlans = [
  {
    id: "free",
    name: "Guest",
    price: 0,
    intervalLabel: "/ visada",
    description: "Trumpa įžanga į Stilloak pasaulį prieš pasirenkant pilną narystę.",
    provider: "internal",
    badge: "Pradžia",
    features: ["Privati paskyra", "Atidarymo peržiūros", "Privati užsakymų istorija"],
  },
  {
    id: "circle",
    name: "Circle",
    price: 10,
    intervalLabel: "/ mėn.",
    description: "Pagrindinė narystė pilnai Stilloak patirčiai: aiškesniems mėnesiams, tikslams ir privačiam archyvui.",
    provider: "stripe",
    badge: "Populiariausia",
    features: [
      "Pilna Stilloak darbo erdvė",
      "Biudžetai, tikslai ir pastovios išlaidos",
      "CSV importas ir mėnesio apžvalga",
      "Savaitinės ir mėnesinės suvestinės",
      "Journal tik nariams",
      "Prioritetinė paskyros priežiūra",
    ],
  },
  {
    id: "private",
    name: "Private",
    price: 20,
    intervalLabel: "/ mėn.",
    description: "Aukštesnis narystės lygis tiems, kurie nori daugiau priežiūros, ramybės ir prioriteto.",
    provider: "stripe",
    badge: "Aukštesnis lygis",
    features: [
      "Viskas iš Circle",
      "Prioritetinė nario priežiūra",
      "Aiškesnė sąskaitų pagalba",
      "Journal tik nariams",
      "Ankstyva prieiga prie atidarymų",
      "Tinka gilesniam nuolatiniam naudojimui",
    ],
  },
];
