import { Plus, Save, ShieldCheck, Trash2, Users } from "lucide-react";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Modal, Notice, PageHeader } from "../components/Ui";
import { api } from "../lib/api";
import type { Podcast } from "../types";

type AdminUser = { id: string; name: string; email: string; role: string; plan: string; lifetimeActive: boolean; paymentStatus: string; active: boolean; signupDate: string; trackedDays: number; lastCheckIn: string | null };

export function AdminPage() {
  const [tab, setTab] = useState<"users"|"podcasts"|"programs">("users"); const [users, setUsers] = useState<AdminUser[]>([]); const [podcasts, setPodcasts] = useState<Podcast[]>([]); const [podcastOpen, setPodcastOpen] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const loadUsers = useCallback(async () => { try { const result = await api<{ users: AdminUser[] }>("/admin/users"); setUsers(result.users); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Could not load users."); } }, []);
  const loadPodcasts = useCallback(async () => { try { const result = await api<{ podcasts: Podcast[] }>("/admin/podcasts"); setPodcasts(result.podcasts); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Could not load podcasts."); } }, []);
  useEffect(() => { void loadUsers(); void loadPodcasts(); }, [loadUsers, loadPodcasts]);
  const resend = async (user: AdminUser, type: string) => { setError(""); try { const result = await api<{ sent: boolean }>(`/admin/users/${user.id}/resend`, { method: "POST", body: { type } }); setMessage(result.sent ? `${type} email sent to ${user.email}.` : "Email was already sent for this period."); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Could not send email."); } };
  return <div className="product-page admin-page"><PageHeader eyebrow="OPERATIONS" title="RESET Admin" description="Users, access, core usage, content, and program controls." action={<span className="admin-badge"><ShieldCheck size={16} /> Admin</span>} /><div className="admin-tabs"><button className={tab === "users" ? "active" : ""} onClick={() => setTab("users")}><Users size={16} />Users</button><button className={tab === "podcasts" ? "active" : ""} onClick={() => setTab("podcasts")}>Podcasts</button><button className={tab === "programs" ? "active" : ""} onClick={() => setTab("programs")}>Programs</button></div>{message && <Notice tone="success">{message}</Notice>}{error && <Notice tone="error">{error}</Notice>}{tab === "users" && <section className="admin-table-wrap"><table><thead><tr><th>User</th><th>Plan</th><th>Payment</th><th>Usage</th><th>Status</th><th>Email</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><strong>{user.name}</strong><small>{user.email}<br />Joined {new Date(user.signupDate).toLocaleDateString()}</small></td><td>{user.lifetimeActive ? "Lifetime" : "Free"}</td><td>{user.paymentStatus}</td><td>{user.trackedDays} days</td><td><span className={`status-pill ${user.active ? "on" : ""}`}>{user.active ? "Active" : "Inactive"}</span></td><td><select aria-label={`Send email to ${user.name}`} defaultValue="" onChange={(event) => { if (event.target.value) void resend(user, event.target.value); event.target.value=""; }}><option value="">Resend…</option><option value="morning">Morning plan</option><option value="evening">Evening check-in</option><option value="weekly">Weekly report</option></select></td></tr>)}</tbody></table></section>}{tab === "podcasts" && <section><div className="admin-section-head"><div><h2>Podcast recommendations</h2><p>Only valid open.spotify.com links are accepted.</p></div><button className="button button-primary" onClick={() => setPodcastOpen(true)}><Plus size={16} />Add</button></div><div className="admin-content-list">{podcasts.map(podcast => <article key={podcast._id}><div><small>{podcast.category} · {podcast.duration}</small><strong>{podcast.title}</strong><span>{podcast.creator}</span></div><button onClick={async () => { await api(`/admin/podcasts/${podcast._id}`, { method: "DELETE" }); await loadPodcasts(); }} aria-label={`Deactivate ${podcast.title}`}><Trash2 size={17} /></button></article>)}</div></section>}{tab === "programs" && <ProgramEditor onSaved={() => setMessage("Program day saved.")} />}<PodcastModal open={podcastOpen} onClose={() => setPodcastOpen(false)} onSaved={async () => { setPodcastOpen(false); await loadPodcasts(); }} /></div>;
}

function PodcastModal({ open, onClose, onSaved }: { open: boolean; onClose: () => void; onSaved: () => void }) {
  const [error, setError] = useState(""); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); try { await api("/admin/podcasts", { method: "POST", body: data }); onSaved(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Could not add podcast."); } };
  return <Modal open={open} title="Add Spotify recommendation" onClose={onClose}><form className="admin-form" onSubmit={submit}>{error && <Notice tone="error">{error}</Notice>}<label>Title<input name="title" required /></label><label>Creator<input name="creator" required /></label><div className="form-grid"><label>Category<select name="category"><option>Discipline</option><option>Business</option><option>Habits</option><option>Focus</option><option>Health</option><option>Sleep</option><option>Money</option><option>Psychology</option></select></label><label>Duration<input name="duration" placeholder="42 min" /></label></div><label>Spotify URL<input name="spotifyUrl" type="url" required placeholder="https://open.spotify.com/episode/..." /></label><label>Description<textarea name="description" /></label><label>Recommended context<input name="recommendedContext" defaultValue="Listen instead of scrolling" /></label><button className="button button-primary">Add recommendation</button></form></Modal>;
}

function ProgramEditor({ onSaved }: { onSaved: () => void }) {
  const [error, setError] = useState(""); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); try { await api(`/admin/programs/${data.duration}/${data.day}`, { method: "PUT", body: data }); onSaved(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Could not save program day."); } };
  return <section className="program-editor"><div className="admin-section-head"><div><h2>Program day override</h2><p>Defaults remain available for every unedited day.</p></div></div><form className="admin-form" onSubmit={submit}>{error && <Notice tone="error">{error}</Notice>}<div className="form-grid"><label>Program<select name="duration"><option value="7">7 days</option><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option></select></label><label>Day<input name="day" type="number" min="1" max="90" required /></label></div><label>Focus<input name="focus" required maxLength={160} /></label><label>Challenge<textarea name="challenge" required maxLength={300} /></label><label>Reflection<textarea name="reflection" required maxLength={300} /></label><button className="button button-primary"><Save size={16} />Save day</button></form></section>;
}
