import { Link } from "react-router-dom";
import { Logo } from "../components/Logo";

const legalContent = {
  privacy: { title: "Privacy Policy", sections: [["What we collect", "Account information, onboarding preferences, habit check-ins, routine progress, self-reported smoking and screen-time information, and technical records needed to keep the service secure."], ["Why we use it", "To provide your requested reset plan, show progress, send emails you enable, process Lifetime access, protect accounts, and improve core reliability."], ["Data choices", "You can disable optional emails, export basic account data, and request account deletion from Settings. Payment card details are handled by Stripe and are not stored by RESET."], ["Legal basis and retention", "We process account and product data to provide the service, security data for legitimate interests, and optional communications with your consent. We retain active account data while the service is used and remove or anonymize deleted accounts, subject to legal obligations."], ["Contact", "For privacy questions or GDPR requests, contact hello@stilloak-studio.com."]] },
  terms: { title: "Terms of Use", sections: [["The service", "RESET by Stilloak is a habit and behaviour tracking product. Free access includes the 7 Day Reset and up to five habits. Founding Lifetime is a one-time purchase for the listed core features; it is not a recurring subscription."], ["Wellness notice", "RESET is not medical treatment, a smoking-cessation programme, diagnosis, or emergency service. It does not replace a doctor or qualified professional. Seek professional support for medical concerns."], ["Your account", "Provide accurate information, keep your sign-in details private, and use the product lawfully. You are responsible for deciding whether any routine or activity is suitable for you."], ["Availability and changes", "We work to keep the service reliable but cannot promise uninterrupted availability. Core updates are included for Lifetime members; separate future products or services may be priced independently."], ["Contact", "Questions about these terms can be sent to hello@stilloak-studio.com."]] },
  cookies: { title: "Cookie Policy", sections: [["Essential session cookie", "RESET uses one HttpOnly, Secure session cookie to keep you signed in and protect access to your account. The cookie is essential for the service and is not used for advertising."], ["No optional tracking by default", "V1 does not load advertising cookies or cross-site analytics. If optional analytics are added later, consent controls and this policy will be updated before they are enabled."], ["Managing cookies", "You can remove the session cookie through your browser or by logging out. Blocking it prevents authenticated product features from working."]] }
};

export function LegalPage({ type }: { type: keyof typeof legalContent }) {
  const content = legalContent[type];
  return <div className="legal-page"><header><Logo /><Link to="/">Back to home</Link></header><main><p className="eyebrow">RESET BY STILLOAK</p><h1>{content.title}</h1><p className="legal-date">Effective: 27 September 2026</p>{content.sections.map(([title, text]) => <section key={title}><h2>{title}</h2><p>{text}</p></section>)}</main></div>;
}
