import { BookOpen, Cigarette, Flame, Smartphone, Sparkles } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { EmptyState, Notice, PageHeader } from "../components/Ui";
import { api } from "../lib/api";
import type { ProgressData } from "../types";

export function ProgressPage() {
  const [range, setRange] = useState<"7"|"30"|"all">("7"); const [data, setData] = useState<ProgressData | null>(null); const [error, setError] = useState("");
  const load = useCallback(async (value: typeof range) => { setError(""); try { setData(await api<ProgressData>(`/progress?range=${value}`)); setRange(value); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Could not load progress."); } }, []);
  useEffect(() => { void load("7"); }, [load]);
  return <div className="product-page"><PageHeader eyebrow="USEFUL, NOT JUDGMENTAL" title="Progress" description="Look for patterns. Keep the changes that make your real days easier." action={<div className="range-tabs">{(["7","30","all"] as const).map(value => <button key={value} className={range === value ? "active" : ""} onClick={() => load(value)}>{value === "all" ? "All time" : `${value} days`}</button>)}</div>} />{error && <Notice tone="error">{error}</Notice>}{data && <><section className="metric-cards"><Metric icon={<Sparkles />} label="Routine" value={`${data.summary.averageCompletion || 0}%`} detail="average completion" /><Metric icon={<Flame />} label="Streak" value={`${data.summary.currentStreak} days`} detail="60%+ completion" /><Metric icon={<Cigarette />} label="Cigarettes" value={data.summary.averageCigarettes == null ? "—" : `${data.summary.averageCigarettes}/day`} detail={`${data.summary.cigarettesAvoided} avoided`} /><Metric icon={<Smartphone />} label="Screen time" value={data.summary.averageScreenTimeMinutes == null ? "—" : formatTime(data.summary.averageScreenTimeMinutes)} detail="daily average" /><Metric icon={<BookOpen />} label="Reading" value={`${data.summary.readingMinutes}m`} detail={`${data.summary.workouts} workouts`} /></section>{data.points.length ? <section className="chart-card"><header><div><p className="eyebrow">ROUTINE COMPLETION</p><h2>Your daily rhythm</h2></div><strong>{data.summary.averageCompletion || 0}% avg.</strong></header><LineChart points={data.points.map(point => point.completion)} labels={data.points.map(point => point.date.slice(5))} /><div className="trend-grid"><MiniTrend title="Cigarettes / day" values={data.points.map(point => point.cigarettes)} suffix="" /><MiniTrend title="Screen time" values={data.points.map(point => point.screenTimeMinutes)} suffix="m" /><MiniTrend title="Mood" values={data.points.map(point => point.mood)} suffix="/5" /></div></section> : <EmptyState title="Your progress starts today" text="Complete routine items and an evening check-in to build your first trend." />}</>}</div>;
}

function Metric({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string }) { return <article className="metric-card"><div>{icon}<span>{label}</span></div><strong>{value}</strong><small>{detail}</small></article>; }
function LineChart({ points, labels }: { points: number[]; labels: string[] }) { const width = 700; const height = 220; const pad = 20; const coords = points.map((value,index) => `${points.length === 1 ? width/2 : pad + index * ((width-pad*2)/(points.length-1))},${height-pad-(value/100)*(height-pad*2)}`).join(" "); return <div className="line-chart"><svg viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none" role="img" aria-label="Routine completion trend"><line x1={pad} y1={height/2} x2={width-pad} y2={height/2} className="grid-line" /><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad} className="grid-line" /><polyline points={coords} fill="none" className="chart-line" />{points.map((value,index) => { const [x,y] = coords.split(" ")[index].split(","); return <circle key={index} cx={x} cy={y} r="5" className="chart-dot"><title>{labels[index]}: {value}%</title></circle>; })}</svg><div>{labels.map((label,index) => <span key={`${label}-${index}`}>{label}</span>)}</div></div>; }
function MiniTrend({ title, values, suffix }: { title: string; values: Array<number|null>; suffix: string }) { const valid = values.filter((value): value is number => value != null); const latest = valid.at(-1); const prior = valid.at(-2); const delta = latest != null && prior != null ? latest-prior : null; return <div><small>{title}</small><strong>{latest == null ? "—" : `${latest}${suffix}`}</strong><span>{delta == null ? "Not enough data" : `${delta > 0 ? "+" : ""}${delta}${suffix} vs previous`}</span></div>; }
const formatTime = (minutes: number) => `${Math.floor(minutes/60)}h ${Math.round(minutes%60)}m`;
