import { BookOpen, Check, ChevronDown, Cigarette, MessageSquareText, MoreHorizontal, RefreshCw, Smartphone, TimerReset, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { EmptyState, Modal, Notice, PageHeader, ProgressRing } from "../components/Ui";
import { api } from "../lib/api";
import { registerTodayTools } from "../lib/webmcp";
import type { RoutineItem, TodayData } from "../types";

const anchors = ["Morning", "Midday", "Afternoon", "Evening", "Before bed"];

export function TodayPage() {
  const [data, setData] = useState<TodayData | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const [sosOpen, setSosOpen] = useState(false); const [boredOpen, setBoredOpen] = useState(false); const [checkInOpen, setCheckInOpen] = useState(new URLSearchParams(location.search).get("checkin") === "1");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setData(await api<TodayData>("/today")); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Could not load today."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => registerTodayTools(), []);
  const grouped = useMemo(() => anchors.map(anchor => [anchor, data?.entry.routine.filter(item => item.anchor === anchor) || []] as const).filter(([,items]) => items.length), [data]);
  const updateItem = async (item: RoutineItem, status: RoutineItem["status"], note = item.note) => { if (!data) return; const previous = data; setData({ ...data, entry: { ...data.entry, routine: data.entry.routine.map(candidate => candidate.key === item.key ? { ...candidate, status, note } : candidate) } }); try { const result = await api<{ entry: TodayData["entry"]; completion: number }>(`/today/items/${encodeURIComponent(item.key)}`, { method: "PATCH", body: { status, note } }); setData(current => current ? { ...current, entry: result.entry, completion: result.completion } : current); } catch (requestError) { setData(previous); setError(requestError instanceof Error ? requestError.message : "Could not update item."); } };
  if (loading) return <TodaySkeleton />;
  if (!data) return <div className="product-page"><Notice tone="error">{error || "Today is unavailable."}</Notice><button className="button button-primary" onClick={load}><RefreshCw size={16} /> Try again</button></div>;
  return (
    <div className="product-page today-page"><PageHeader eyebrow={`${new Date(`${data.date}T12:00:00`).toLocaleDateString("en", { weekday: "long", month: "long", day: "numeric" })} · Day ${data.day} of ${data.duration}`} title="Today" description="Complete the next useful action. The rest can wait." action={<ProgressRing value={data.completion} />} />{error && <Notice tone="error">{error}</Notice>}
      <section className="focus-card"><div><small>DAY {data.day} FOCUS</small><h2>{data.program.focus}</h2><p>{data.program.challenge}</p></div><span>{String(data.day).padStart(2,"0")}</span></section>
      <div className="today-layout"><section className="routine-card"><header><div><p className="eyebrow">YOUR ROUTINE</p><h2>{data.entry.routine.filter(item => item.status === "done").length} of {data.entry.routine.length} complete</h2></div><button className="button button-small button-ghost" onClick={() => setCheckInOpen(true)}>Evening check-in</button></header>{grouped.length ? grouped.map(([anchor, items]) => <div className="routine-group" key={anchor}><p className="anchor-label">{anchor}</p>{items.map(item => <RoutineRow key={item.key} item={item} onUpdate={updateItem} />)}</div>) : <EmptyState title="No actions yet" text="Add a habit or rebuild your onboarding plan." />}</section>
        <aside className="today-sidebar"><section className="mini-panel smoking-panel"><header><div className="panel-icon"><Cigarette /></div><div><small>SMOKING</small><strong>{data.entry.cigarettes ?? 0} / {data.entry.cigaretteTarget ?? 0}</strong></div></header><div className="panel-progress"><i style={{ width: `${Math.min(100, ((data.entry.cigarettes || 0) / Math.max(1, data.entry.cigaretteTarget || 1)) * 100)}%` }} /></div><div className="panel-metrics"><span>Delayed<strong>{data.smoking.cravingsDelayed}</strong></span><span>Avoided<strong>{data.smoking.cigarettesAvoided}</strong></span><span>Avg. gap<strong>{data.smoking.averageIntervalMinutes ? `${data.smoking.averageIntervalMinutes}m` : "—"}</strong></span></div><div className="panel-actions"><button className="button button-primary" onClick={() => setSosOpen(true)}>I want to smoke</button><LogCigarette onSaved={load} /></div></section>
          <section className="mini-panel screen-panel"><header><div className="panel-icon"><Smartphone /></div><div><small>SCREEN TIME</small><strong>{data.entry.screenTimeMinutes == null ? "Not logged" : formatMinutes(data.entry.screenTimeMinutes)}</strong></div></header><p>Daily target: {formatMinutes(data.entry.screenTargetMinutes || 0)}</p><button className="button button-ghost" onClick={() => setBoredOpen(true)}>I'm bored</button></section>
          <section className="mini-panel reflection-panel"><small>TONIGHT'S REFLECTION</small><h3>{data.program.reflection}</h3><button onClick={() => setCheckInOpen(true)}>Write check-in <MessageSquareText size={16} /></button></section>
          {data.podcast && <section className="mini-panel podcast-mini"><BookOpen /><div><small>{data.podcast.recommendedContext}</small><strong>{data.podcast.title}</strong><span>{data.podcast.creator} · {data.podcast.duration}</span></div><a href={data.podcast.spotifyUrl} target="_blank" rel="noreferrer">Listen</a></section>}
        </aside></div>
      <SmokeSos open={sosOpen} onClose={() => setSosOpen(false)} onResolved={load} />
      <BoredModal open={boredOpen} onClose={() => setBoredOpen(false)} />
      <EveningCheckIn open={checkInOpen} data={data} onClose={() => setCheckInOpen(false)} onSaved={(entry) => setData(current => current ? { ...current, entry } : current)} />
    </div>
  );
}

function RoutineRow({ item, onUpdate }: { item: RoutineItem; onUpdate: (item: RoutineItem, status: RoutineItem["status"], note?: string) => void }) {
  const [noteOpen, setNoteOpen] = useState(Boolean(item.note)); const [note, setNote] = useState(item.note);
  return <article className={`routine-row status-${item.status}`}><button className="task-check" onClick={() => onUpdate(item, item.status === "done" ? "pending" : "done")} aria-label={item.status === "done" ? `Mark ${item.title} pending` : `Mark ${item.title} done`}>{item.status === "done" && <Check size={15} />}{item.status === "skipped" && <X size={14} />}</button><div className="task-time">{item.time || item.anchor}</div><div className="task-copy"><strong>{item.title}</strong>{item.source === "habit" && <small>Habit</small>}{noteOpen && <div className="task-note"><input value={note} onChange={event => setNote(event.target.value)} placeholder="Optional note" maxLength={400} onBlur={() => onUpdate(item, item.status, note)} /><button onClick={() => { setNote(""); setNoteOpen(false); onUpdate(item, item.status, ""); }} aria-label="Remove note"><X size={14} /></button></div>}</div><div className="task-actions"><button onClick={() => onUpdate(item, "done")}>Done</button><button onClick={() => onUpdate(item, "skipped")}>Skip</button><button aria-label="Add note" onClick={() => setNoteOpen(value => !value)}><MoreHorizontal size={18} /></button></div></article>;
}

function LogCigarette({ onSaved }: { onSaved: () => void }) {
  const [saving, setSaving] = useState(false); const log = async () => { setSaving(true); try { await api("/today/smoking/cigarette", { method: "POST", body: {} }); onSaved(); } finally { setSaving(false); } };
  return <button className="button button-ghost" onClick={log} disabled={saving}>{saving ? "Saving…" : "+ Log cigarette"}</button>;
}

function SmokeSos({ open, onClose, onResolved }: { open: boolean; onClose: () => void; onResolved: () => void }) {
  const [stage, setStage] = useState<"setup"|"timer"|"answer">("setup"); const [seconds, setSeconds] = useState(600); const [cravingId, setCravingId] = useState(""); const [level, setLevel] = useState(3); const [trigger, setTrigger] = useState("Stress");
  useEffect(() => { if (!open || stage !== "timer") return; const timer = window.setInterval(() => setSeconds(value => { if (value <= 1) { window.clearInterval(timer); setStage("answer"); return 0; } return value - 1; }), 1000); return () => window.clearInterval(timer); }, [open, stage]);
  const start = async () => { const result = await api<{ craving: { _id: string } }>("/today/smoking/cravings", { method: "POST", body: { level, trigger } }); setCravingId(result.craving._id); setSeconds(600); setStage("timer"); };
  const resolve = async (stillWanted: boolean) => { await api(`/today/smoking/cravings/${cravingId}`, { method: "PATCH", body: { stillWanted } }); onResolved(); setStage("setup"); onClose(); };
  const close = () => { if (stage !== "timer") setStage("setup"); onClose(); };
  return <Modal open={open} title={stage === "setup" ? "Pause the craving" : stage === "timer" ? "Give it ten minutes" : "Check in honestly"} onClose={close}>{stage === "setup" && <div className="sos-content"><p>This is a short behaviour-change pause, not medical treatment. Name the urge, then give yourself ten minutes.</p><label>Craving level <span>{level}/5</span><input type="range" min="1" max="5" value={level} onChange={event => setLevel(Number(event.target.value))} /></label><label>Trigger<select value={trigger} onChange={event => setTrigger(event.target.value)}><option>Stress</option><option>Boredom</option><option>After food</option><option>Social situation</option><option>Habit</option><option>Other</option></select></label><button className="button button-primary button-large" onClick={start}><TimerReset /> Start 10 min pause</button></div>}{stage === "timer" && <div className="timer-content"><div className="countdown">{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</div><p>Choose one action while the timer runs.</p><div className="coping-grid"><span>Drink water</span><span>Short walk</span><span>Slow breathing</span><span>Chew gum</span><span>Read one page</span><span>Do a small task</span><span>Play a podcast</span></div><button className="text-button" onClick={() => setStage("answer")}>Check in now</button></div>}{stage === "answer" && <div className="answer-content"><p>Do you still want to smoke?</p><div><button className="button button-ghost" onClick={() => resolve(true)}>Yes</button><button className="button button-primary" onClick={() => resolve(false)}>No</button></div></div>}</Modal>;
}

function BoredModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [minutes, setMinutes] = useState(15); const [suggestions, setSuggestions] = useState<string[]>([]);
  const choose = async (value: number) => { setMinutes(value); const result = await api<{ suggestions: string[] }>(`/today/bored/${value}`); setSuggestions(result.suggestions); };
  return <Modal open={open} title="How much time do you have?" onClose={onClose}><div className="time-options">{[[5,"5 min"],[15,"15 min"],[30,"30 min"],[60,"1 hour"],[120,"2 hours"]].map(([value,label]) => <button className={minutes === value ? "active" : ""} key={value} onClick={() => choose(value as number)}>{label}</button>)}</div>{suggestions.length ? <div className="suggestion-list">{suggestions.map((item,index) => <button key={item}><span>{index+1}</span>{item}<ChevronDown size={16} /></button>)}</div> : <p className="muted">Choose a time window. RESET will give you a few useful alternatives to scrolling.</p>}</Modal>;
}

function EveningCheckIn({ open, onClose, data, onSaved }: { open: boolean; onClose: () => void; data: TodayData; onSaved: (entry: TodayData["entry"]) => void }) {
  const [error, setError] = useState(""); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const result = await api<{ entry: TodayData["entry"] }>("/today/check-in", { method: "POST", body: { ...values, workout: values.workout === "yes" } }); onSaved(result.entry); onClose(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Could not save check-in."); } };
  return <Modal open={open} title="Evening check-in" onClose={onClose}><form className="checkin-form" onSubmit={submit}>{error && <Notice tone="error">{error}</Notice>}<div className="form-grid"><label>Cigarettes today<input name="cigarettes" type="number" min="0" max="200" defaultValue={data.entry.cigarettes ?? ""} /></label><label>Screen time (minutes)<input name="screenTimeMinutes" type="number" min="0" max="1440" defaultValue={data.entry.screenTimeMinutes ?? ""} /></label><label>Workout?<select name="workout" defaultValue={data.entry.workout ? "yes" : "no"}><option value="yes">Yes</option><option value="no">No</option></select></label><label>Reading (minutes)<input name="readingMinutes" type="number" min="0" max="600" defaultValue={data.entry.readingMinutes ?? ""} /></label><label>Mood 1–5<input name="mood" type="number" min="1" max="5" defaultValue={data.entry.mood ?? 3} /></label></div><label>What went well?<textarea name="wentWell" maxLength={500} defaultValue={data.entry.wentWell} placeholder="One honest sentence is enough." /></label><button className="button button-primary">Save check-in</button></form></Modal>;
}

const formatMinutes = (minutes: number) => `${Math.floor(minutes / 60)}h ${minutes % 60}m`;
function TodaySkeleton() { return <div className="product-page"><div className="skeleton title" /><div className="skeleton hero" /><div className="today-layout"><div className="skeleton list" /><div className="skeleton side" /></div></div>; }
