const escapeHtml = (value) => String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
const LOGO_URL = process.env.EMAIL_LOGO_URL?.trim() || "https://web.stilloak-studio.com/stilloak-logo.svg";

const buildWebServiceEmail = ({ subject, preheader, name, title, intro, rows = [], cta = null, notice = "" }) => {
  const textRows = rows.map(({ label, value }) => `${label}: ${value}`);
  const text = [`Sveiki, ${name},`, "", intro, ...textRows, cta?.url ? `Atidaryti: ${cta.url}` : null, notice || null, "", "Stilloak Web", "hello@stilloak-studio.com"].filter(Boolean).join("\n");
  const rowHtml = rows.map(({ label, value }) => `<tr><td style="padding:10px 0;color:#75695d">${escapeHtml(label)}</td><td style="padding:10px 0;text-align:right;font-weight:700">${escapeHtml(value)}</td></tr>`).join("");
  const html = `<!doctype html><html lang="lt"><body style="margin:0;padding:24px;background:#f4f1ec;font-family:Arial,sans-serif;color:#201d19"><span style="display:none!important">${escapeHtml(preheader || subject)}</span><table role="presentation" width="100%"><tr><td align="center"><table role="presentation" width="640" style="max-width:100%;background:#fff;border:1px solid #e5ddd3;border-radius:22px"><tr><td style="padding:32px"><table role="presentation"><tr><td style="padding-right:14px"><img src="${escapeHtml(LOGO_URL)}" width="46" height="46" alt="Stilloak Web" style="display:block;border-radius:12px"></td><td><strong style="font-size:18px">Stilloak Web</strong><div style="font-size:11px;letter-spacing:.18em;color:#8a6c46;text-transform:uppercase;margin-top:4px">Svetainių projektai</div></td></tr></table><h1 style="font-size:28px;line-height:1.2;margin:26px 0 14px">${escapeHtml(title)}</h1><p style="font-size:15px;line-height:1.7;color:#655b50">Sveiki, ${escapeHtml(name)}. ${escapeHtml(intro)}</p>${rowHtml ? `<table role="presentation" width="100%" style="margin:22px 0;border-top:1px solid #e5ddd3;border-bottom:1px solid #e5ddd3">${rowHtml}</table>` : ""}${cta?.url ? `<p style="margin:24px 0"><a href="${escapeHtml(cta.url)}" style="display:inline-block;background:#201d19;color:white;text-decoration:none;border-radius:999px;padding:13px 20px;font-weight:700">${escapeHtml(cta.label)}</a></p>` : ""}${notice ? `<p style="padding:14px 16px;background:#fff7e8;border:1px solid #ead9b8;border-radius:14px;color:#765d35;font-size:13px;line-height:1.6">${escapeHtml(notice)}</p>` : ""}<p style="margin-top:24px;font-size:13px;color:#8a8177">Pagalba: <a href="mailto:hello@stilloak-studio.com" style="color:#8a6c46">hello@stilloak-studio.com</a></p></td></tr></table></td></tr></table></body></html>`;
  return { subject, text, html };
};

module.exports = { buildWebServiceEmail, escapeHtml };
