const escapeHtml = (value) => String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
const LOGO_URL = process.env.EMAIL_LOGO_URL?.trim() || "https://web.stilloak-studio.com/stilloak-logo.svg";

const buildWebServiceEmail = ({ subject, preheader, name, title, intro, rows = [], cta = null, notice = "" }) => {
  const textRows = rows.map(({ label, value }) => `${label}: ${value}`);
  const text = [`Sveiki, ${name},`, "", intro, ...textRows, cta?.url ? `Atidaryti: ${cta.url}` : null, notice || null, "", "Stilloak Web", "hello@stilloak-studio.com"].filter(Boolean).join("\n");
  const rowHtml = rows.map(({ label, value }) => `<tr><td style="width:42%;padding:11px 12px 11px 0;color:#75695d;text-align:left;vertical-align:top;line-height:1.5;word-break:break-word">${escapeHtml(label)}</td><td style="padding:11px 0 11px 12px;text-align:left;vertical-align:top;font-weight:700;line-height:1.5;word-break:break-word">${escapeHtml(value)}</td></tr>`).join("");
  const html = `<!doctype html><html lang="lt"><body style="margin:0;padding:0;background:#f4f1ec;font-family:Arial,Helvetica,sans-serif;color:#201d19;text-align:left"><span style="display:none!important;max-height:0;overflow:hidden;opacity:0">${escapeHtml(preheader || subject)}</span><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;border-collapse:collapse;background:#f4f1ec;text-align:left"><tr><td align="center" style="padding:24px 12px"><table role="presentation" width="640" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:640px;border-collapse:separate;background:#fff;border:1px solid #e5ddd3;border-radius:22px;text-align:left"><tr><td style="padding:32px 28px;text-align:left"><table role="presentation" cellspacing="0" cellpadding="0" border="0" style="border-collapse:collapse;text-align:left"><tr><td style="padding-right:14px;vertical-align:middle"><img src="${escapeHtml(LOGO_URL)}" width="46" height="46" alt="Stilloak Web" style="display:block;border:0;border-radius:12px"></td><td style="vertical-align:middle;text-align:left"><strong style="font-size:18px;line-height:1.25">Stilloak Web</strong><div style="margin-top:4px;font-size:11px;line-height:1.4;letter-spacing:.18em;color:#8a6c46;text-transform:uppercase">Svetainių projektai</div></td></tr></table><h1 style="margin:26px 0 14px;font-size:28px;line-height:1.25;text-align:left">${escapeHtml(title)}</h1><p style="margin:0;font-size:15px;line-height:1.7;color:#655b50;text-align:left">Sveiki, ${escapeHtml(name)}.</p><p style="margin:8px 0 0;font-size:15px;line-height:1.7;color:#655b50;text-align:left">${escapeHtml(intro)}</p>${rowHtml ? `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:22px 0;border-collapse:collapse;border-top:1px solid #e5ddd3;border-bottom:1px solid #e5ddd3;text-align:left">${rowHtml}</table>` : ""}${cta?.url ? `<table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin:24px 0;text-align:left"><tr><td style="border-radius:999px;background:#201d19;text-align:center"><a href="${escapeHtml(cta.url)}" style="display:inline-block;padding:13px 20px;color:#fff;text-decoration:none;font-weight:700;line-height:1.4;text-align:center">${escapeHtml(cta.label)}</a></td></tr></table>` : ""}${notice ? `<p style="margin:20px 0 0;padding:14px 16px;background:#fff7e8;border:1px solid #ead9b8;border-radius:14px;color:#765d35;font-size:13px;line-height:1.6;text-align:left">${escapeHtml(notice)}</p>` : ""}<p style="margin:24px 0 0;font-size:13px;line-height:1.6;color:#8a8177;text-align:left">Pagalba: <a href="mailto:hello@stilloak-studio.com" style="color:#8a6c46">hello@stilloak-studio.com</a></p></td></tr></table></td></tr></table></body></html>`;
  return { subject, text, html };
};

module.exports = { buildWebServiceEmail, escapeHtml };
