const escapeHtml = (value) => String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");

const LOGO_URL = process.env.EMAIL_LOGO_URL?.trim() || "https://web.stilloak-studio.com/stilloak-logo.svg";
const SUPPORT_EMAIL = "hello@stilloak-studio.com";

const buildDetailRows = (rows) => rows.map(({ label, value }) => `
  <tr>
    <td style="padding:0 0 10px;text-align:left;">
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;border-collapse:separate;background:#f8f5f1;border:1px solid #ece4dc;border-radius:12px;">
        <tr><td style="padding:13px 16px 4px;font-family:Arial,Helvetica,sans-serif;font-size:10px;line-height:1.4;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:#8b7767;text-align:left;">${escapeHtml(label)}</td></tr>
        <tr><td style="padding:0 16px 13px;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.55;font-weight:700;color:#29231f;text-align:left;word-break:break-word;overflow-wrap:anywhere;">${escapeHtml(value)}</td></tr>
      </table>
    </td>
  </tr>`).join("");

const buildWebServiceEmail = ({ subject, preheader, name, title, intro, body = "", rows = [], cta = null, notice = "" }) => {
  const textRows = rows.map(({ label, value }) => `${label}: ${value}`);
  const text = [`Sveiki, ${name},`, "", intro, body || null, "", ...textRows, cta?.url ? `Atidaryti: ${cta.url}` : null, notice || null, "", "Stilloak Web", SUPPORT_EMAIL].filter(Boolean).join("\n");
  const rowHtml = buildDetailRows(rows);
  const html = `<!doctype html><html lang="lt"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="x-apple-disable-message-reformatting"><title>${escapeHtml(subject)}</title><style>@media only screen and (max-width:480px){.email-shell{padding:14px 8px!important}.email-card{border-radius:16px!important}.email-header{padding:22px 20px 18px!important}.email-content{padding:24px 20px!important}.email-title{font-size:26px!important;line-height:1.18!important}.email-footer{padding:20px!important}.email-button{display:block!important;padding:14px 16px!important}}</style></head>
<body style="margin:0;padding:0;background:#eee9e3;font-family:Arial,Helvetica,sans-serif;color:#29231f;text-align:left;"><span style="display:none!important;max-height:0;max-width:0;overflow:hidden;opacity:0;color:transparent;">${escapeHtml(preheader || subject)}&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;</span>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;border-collapse:collapse;background:#eee9e3;"><tr><td class="email-shell" align="center" style="padding:32px 12px;">
<!--[if mso]><table role="presentation" width="640" cellspacing="0" cellpadding="0" border="0"><tr><td><![endif]-->
<table class="email-card" role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:640px;border-collapse:separate;background:#ffffff;border:1px solid #ddd4cb;border-radius:22px;box-shadow:0 12px 36px rgba(56,43,33,.08);overflow:hidden;text-align:left;">
<tr><td class="email-header" style="padding:26px 30px 22px;background:#211d1a;text-align:left;"><table role="presentation" cellspacing="0" cellpadding="0" border="0" style="border-collapse:collapse;"><tr><td style="padding-right:13px;vertical-align:middle;"><img src="${escapeHtml(LOGO_URL)}" width="44" height="44" alt="Stilloak Web" style="display:block;width:44px;height:44px;border:0;border-radius:11px;"></td><td style="vertical-align:middle;text-align:left;"><div style="font-family:Arial,Helvetica,sans-serif;font-size:18px;line-height:1.2;font-weight:700;color:#ffffff;">Stilloak <span style="color:#d7b58e;">Web</span></div><div style="margin-top:5px;font-family:Arial,Helvetica,sans-serif;font-size:9px;line-height:1.4;font-weight:700;letter-spacing:.18em;text-transform:uppercase;color:#b9aca1;">Svetainių projektai</div></td></tr></table></td></tr>
<tr><td class="email-content" style="padding:32px 30px 30px;text-align:left;"><div style="display:inline-block;margin:0 0 15px;padding:6px 10px;border-radius:999px;background:#efe5da;font-family:Arial,Helvetica,sans-serif;font-size:10px;line-height:1.4;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#79563d;">Stilloak Web pranešimas</div><h1 class="email-title" style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:30px;line-height:1.2;letter-spacing:-.025em;color:#211d1a;text-align:left;">${escapeHtml(title)}</h1><p style="margin:20px 0 0;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#4f4741;text-align:left;">Sveiki, <strong style="color:#29231f;">${escapeHtml(name)}</strong>,</p><p style="margin:8px 0 0;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#625951;text-align:left;">${escapeHtml(intro)}</p>${body ? `<p style="margin:12px 0 0;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#625951;text-align:left;white-space:pre-line;word-break:break-word;">${escapeHtml(body)}</p>` : ""}${rowHtml ? `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:24px 0 0;border-collapse:collapse;text-align:left;">${rowHtml}</table>` : ""}${cta?.url ? `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:24px 0 0;border-collapse:collapse;"><tr><td style="border-radius:12px;background:#7b5338;text-align:center;"><a class="email-button" href="${escapeHtml(cta.url)}" style="display:block;padding:14px 20px;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.4;font-weight:700;color:#ffffff;text-decoration:none;text-align:center;">${escapeHtml(cta.label)} &nbsp;→</a></td></tr></table>` : ""}${notice ? `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:20px 0 0;border-collapse:separate;background:#fff8e9;border:1px solid #e9d9b7;border-radius:12px;"><tr><td style="width:4px;background:#c6954e;border-radius:12px 0 0 12px;"></td><td style="padding:13px 15px;font-family:Arial,Helvetica,sans-serif;font-size:12px;line-height:1.65;color:#6f5937;text-align:left;">${escapeHtml(notice)}</td></tr></table>` : ""}<p style="margin:25px 0 0;font-family:Arial,Helvetica,sans-serif;font-size:12px;line-height:1.65;color:#8a8179;text-align:left;">Kilo klausimų? Atsakykite į šį laišką arba parašykite <a href="mailto:${SUPPORT_EMAIL}" style="color:#79563d;font-weight:700;text-decoration:none;">${SUPPORT_EMAIL}</a>.</p></td></tr>
<tr><td class="email-footer" style="padding:20px 30px;background:#f5f1ed;border-top:1px solid #e8e0d8;text-align:left;"><p style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:11px;line-height:1.65;color:#81776f;text-align:left;">Stilloak Web · profesionalių svetainių kūrimas</p><p style="margin:3px 0 0;font-family:Arial,Helvetica,sans-serif;font-size:11px;line-height:1.65;color:#a0968e;text-align:left;">Šis laiškas susijęs su jūsų pateikta užklausa arba projektu.</p></td></tr></table>
<!--[if mso]></td></tr></table><![endif]--></td></tr></table></body></html>`;
  return { subject, text, html };
};

module.exports = { buildWebServiceEmail, escapeHtml };
